INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'A épica jornada do Comandante Shepard para salvar a galáxia da aniquilação pelos Ceifadores. Suas escolhas definem o destino de todas as espécies.', 'Uma mistura magistral de RPG de ação e shooter tático com um foco profundo na narrativa e nos personagens. Comande a nave Normandy, monte sua equipe ideal e decida o destino de mundos inteiros através de um sistema de diálogo e escolhas morais que definem sua experiência única.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'A história épica de Arthur Morgan e da gangue Van der Linde em fuga em uma América cruel e em transformação. Uma luta brutal pela sobrevivência onde honra e lealdade são colocadas à prova!', 'Red Dead Redemption 2 é um drama visceral sobre lealdade, liberdade e o custo da redenção. Comande a gangue Van der Linde em sua queda inexorável, tomando decisões morais em um mundo aberto impressionante que respira e reage a cada um de seus atos.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Em um mundo devastado pela guerra e assolado por monstros, Geralt de Rivia parte em uma jornada épica para encontrar sua filha adotiva, Ciri, antes que a Caçada Selvagem a capture. Cada escolha tem um preço.', 'The Witcher 3: Wild Hunt é uma masterclass em narrativa e mundo aberto. Como Geralt de Rivia, o lendário bruxo caçador de monstros, sua missão pessoal se entrelaça com o destino político de reinos inteiros. Explore um continente vasto e repleto de histórias, onde suas decisões moldam profundamente as pessoas, os lugares e o desfecho final da sua saga.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Como o lobo de um braço só, Sekiro, embarque em uma missão de redenção e vingança para resgatar seu jovem lorde e restaurar sua honra. Em um Japão feudal mitológico, a morte é apenas o começo!', 'Sekiro: Shadows Die Twice é um desafio intenso de ação e aventura da FromSoftware. Domine o combate visceral de espadas, onde postura e deflexão precisas são a chave para a vitória. Explore um mundo interconectado repleto de perigos, segredos e inimigos colossais. Use seu braço prostético e a habilidade de voltar da morte para superar adversidades impossíveis em uma jornada implacável de lealdade e retribuição.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Jin Sakai, um dos últimos samurais de Tsushima, precisa abandonar o código que define sua honra para proteger seu povo e libertar sua ilha da invasão mongol. Uma jornada de sacrifício e vingança!', 'Ghost of Tsushima é um épico cinematográfico de mundo aberto que coloca você na pele de Jin Sakai. Em sua luta desesperada contra a brutal invasão mongol, ele precisa dominar um novo estilo de luta — o Caminho do Fantasma. Explore os campos, florestas e montanhas da deslumbrante ilha de Tsushima, entrando em combates de katana precisos e letais. Suas escolhas entre a tradição samurai e a tática furtiva do fantasma moldarão o destino de toda a ilha.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Mario e Luigi partem em uma aventura colorida através de Dinosaur Land para resgatar a Princesa Peach das garras do Bowser e de seus novos capangas, os Koopalings!', 'Super Mario World é um marco dos jogos de plataforma. Explore um mundo vasto e interconectado repleto de segredos, power-ups clássicos e fases criativas. Domine as habilidades de voo com a Cape Feather e faça amizade com Yoshi, o dinossauro companheiro, para descobrir caminhos alternativos e desafios secretos nesta jornada atemporal para salvar o reino.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Explore as profundezas de Hallownest, um reino arruinado de insetos e heróis. Enfrente criaturas grotescas, desvende segredos antigos e recupere sua honra em um metroidvania desafiador e atmosférico!', 'Hollow Knight é uma aventura de ação e exploração em um vasto mundo interconectado. Com sua agilidade e ''nail'' afiado, enfrente criaturas peculiares, desbloqueie habilidades novas e descubra caminhos secretos. Aprofunde-se em uma narrativa ambiental rica, encontre personagens misteriosos e decida o destino deste reino consumido por uma infecção sobrenatural, em uma experiência metroidvania imersiva e poeticamente sombria.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Embarque na jornada emocionante de Ori, um pequeno espírito destinado a restaurar a floresta de Nibel, corrompida por uma força sombria. Uma fábula sobre esperança e sacrifício!', 'Ori and the Blind Forest é uma obra-prima visual e emocional do gênero metroidvania. Guie Ori através de paisagens deslumbrantes e perigosas, usando habilidades ágeis e magia ancestral. Cada novo poder desbloqueia áreas secretas em um mundo interconectado, enquanto você desvenda uma história comovente sobre amor, perda e a luz que persiste mesmo na escuridão mais profunda.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Cuphead e Mugman encaram uma missão frenética para derrotar devedores astutos e recuperar suas almas do diabo. Inspirado nos desenhos animados clássicos dos anos 30, com pura ação e estilo!', 'Cuphead é um shooter de corrida e ação com uma identidade visual única, meticulosamente animada no estilo dos desenhos animados da era de ouro. Lute contra uma galeria de chefes exagerados e desafiadores em batalhas intensas que exigem reflexos rápidos e paciência. Explore mundos vibrantes, desbloqueie armas e habilidades especiais, e mergulhe em uma aventura com trilha sonora de jazz original que é tanto uma celebração da arte quanto um teste de habilidade.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Sonic acelera através do tempo para salvar Little Planet e derrotar o Dr. Robotnik, evitando um futuro catastrófico. Velocidade, viagem no tempo e uma trilha sonora icônica definem esta aventura clássica!', 'Sonic CD eleva a jogabilidade do ouriço mais rápido do mundo com a adição da viagem no tempo. Explore as fases de forma única, viajando entre passado, presente e futuro para alterar o destino de Little Planet. Com uma jogabilidade de alta velocidade, design de fases complexo e duas trilhas sonoras lendárias, esta aventura é um marco essencial que define a identidade e a ambição da franquia Sonic the Hedgehog.');

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);